#!/usr/bin/env python
# created by:
# Sebastian Fornfischer
# sebastian.fornfischer@prosiebensat1.com

# date:  2018/09/12

# file location:
# share/check_mk/checks/


def inventory_slfr_cluster_members(info):
  yield 'ensembleMembers', None

def check_slfr_cluster_members(item, params, info):

    if 0 == len(info):
     return 3, 'info is zero length'
    else:
     return 0, "Ensemble Members: " + str(info[0][1]) + " " + str(info[0][2]) + " " + str(info[0][3])

check_info['slfr_cluster_members'] = {
  'check_function':            check_slfr_cluster_members,
  'inventory_function':        inventory_slfr_cluster_members,
  'service_description':       'SLFR-CLUSTER-MEMBERS-%s',
}
