#!/usr/bin/env python
# created by:
# Sebastian Fornfischer
# sebastian.fornfischer@prosiebensat1.com

# date:  2018/09/12

# file location:
# share/check_mk/checks/


def inventory_slfr_cluster_faults(info):
  yield 'clusterFaults', None

def check_slfr_cluster_faults(item, params, info):

    if 0 == len(info):
     return 3, 'info is zero length'
    elif info[0][1] == "None":
     return 0, "Faults: " + str(info[0][1])
    else:
     return 2, "Faults: " + str(info[0][1])


check_info['slfr_cluster_faults'] = {
  'check_function':            check_slfr_cluster_faults,
  'inventory_function':        inventory_slfr_cluster_faults,
  'service_description':       'SLFR-CLUSTER-FAULTS-%s',
}

